### ISSUE TITLE
Problems using _type with index templates and other use cases

### ISSUE THREAD

**Issue by ninodafonte** [broadway/read-model-elasticsearch#32]
Hey team!

First of all, thank you for your work here, it's a great library and has helped me a lot. 

Just wanted to ask if there are any plans from your side to remove the _type field from the repository (as it creates trouble starting in ES 7.0) and it will disappear soon (as I'm sure you already know). 

I did some changes in a fork (basically just removed the references to 'type' all over the repository and created a custom serializer to be able to use a _class field inside the payload as a reference instead the type field. It works for me although I'm pretty sure there is a better solution for this case so, I'm asking:

- If you already have any plans to fix this, please let me know, I'm happy to take that task myself if you give me some guidance in what you think is the right implementation.

Thank you and keep the good work!

**Comment by othillo** [comment]
Hi, @ninodafonte, thank you! We don't have plans to remove it. Can you share your changes in a PR so we can discuss it?

**Comment by ninodafonte** [comment]
Hi @othillo , 

Just created #33 to start talking about it. Happy to see how do you think we should approach it.

Cheers,

**Comment by othillo** [comment]
fixed by #33
